name: build

on: push

env:
  VCINSTALLDIR: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/
  Qt5_DIR: Qt\5.13.1\msvc2017_64\lib\cmake\Qt5\
  QTDIR: Qt\5.13.1\msvc2017_64\

jobs:
  windows:
    timeout-minutes: 60
    runs-on: windows-2019

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Prepare
      working-directory: build
      shell: cmd
      run: |
        curl -vLo qt-opensource-windows-x86-5.14.0.exe http://download.qt.io/official_releases/qt/5.14/5.14.0/qt-opensource-windows-x86-5.14.0.exe 
        qt-opensource-windows-x86-5.14.0.exe --verbose --script ..\ci\qt.qs 

    - name: Configure
      working-directory: build
      shell: cmd
      run: |
        echo Hier
        echo %CMAKE_MODULE_PATH%
        echo %PATH%
        dir /s Qt
        cmake -DCMAKE_PREFIX_PATH=Qt -DCPACK_IFW_ROOT=Qt/Tools/QtInstallerFramework/3.1 -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" ..

    - name: Compile
      working-directory: build
      shell: cmd
      run: cmake --build . --config Release -j 4

    - name: Package
      working-directory: build
      shell: cmd
      run: cmake --build . --config Release --target package

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/gh-greets-qt_installer.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
